### ISSUE TITLE
"unknown encoding: iso7811-t1" error when running on Python 3.9.5

### ISSUE THREAD

**Issue by DesiOtaku** [oxplot/msrx#4]
I am getting a "unknown encoding: iso7811-t1" error when running a newer version of Python (3.9.5). Still works fine for older versions of python.

Full error stack:

> Traceback (most recent call last):
>   File "/usr/local/bin/msrx", line 6, in <module>
>     msrx.main()
>   File "/usr/local/lib/python3.9/dist-packages/msrx/__init__.py", line 379, in main
>     args.func(args)
>   File "/usr/local/lib/python3.9/dist-packages/msrx/__init__.py", line 261, in _do_write
>     data = [
>   File "/usr/local/lib/python3.9/dist-packages/msrx/__init__.py", line 262, in <listcomp>
>     _DATA_CONV[args.type, 'raw'](d, t + 1)
>   File "/usr/local/lib/python3.9/dist-packages/msrx/__init__.py", line 227, in <lambda>
>     ('iso', 'raw'): (lambda d, t: codecs.decode(d, 'iso7811-t%d' % t))
> LookupError: unknown encoding: iso7811-t1

**Comment by oxplot** [comment]
Thanks for the report — fix coming up.
