### ISSUE TITLE
Better installation instructions

### ISSUE THREAD

**Issue by wetbadger** [oxplot/msrx#5]
Obviously just typing "pip install msrx" will not allow msrx to be run as a _bash command_. More detailed instructions would be helpful.

**Comment by oxplot** [comment]
> Obviously just typing "pip install msrx" will not allow msrx to be run as a _bash command_.

It should. I just did a test:

```
$ virtualenv myenv
$ . myenv/bin/activate
$ pip install msrx
$ which msrx
/home/mike/tmp/venv/bin/msrx
$ msrx -h
usage: msrx [-h] [-D DEV] [-R] [--version] {read,write,erase} ...

Library and command line utils to use MSR605 magnetic card reader/writer
...
```
