### ISSUE TITLE
Find out how to point to the device

### ISSUE THREAD

**Issue by manny880** [oxplot/msrx#6]
Hi,

I am sorry in advance, I understand this question is not directly related to your software.
I am trying to get my device working on an arch based distribution, and, I have nothing looking like `/dev/ttyUSB*`.
I tried `lsusb` that shows the msrx device plugged in:

`Bus 001 Device 004: ID 0801:0003 MagTek Magstripe Insert Reader`

Any help finding out how to properly point to the device would be greatly appreciated. Thanks for your time.

**Comment by oxplot** [comment]
Doing a quick Google search shows that MagTeks don't show up as serial devices. Here's another project that may be of interest: https://github.com/MicahCarrick/magtek-pyusb

**Comment by manny880** [comment]
Thanks a lot for your help. It is too bad that I cannot use your software then with my device, I am going to look into this other project then. I hope it works. Thanks again.

**Comment by manny880** [comment]
Unfortunately, it seems (skimming thru the code) that `magtek-pyusb` is specifically designed to read credit cards, and it does not seem to be able to write. I am not reading credit cards, I need to write custom magstripes.

I finally tried the vendor software (of course only designed for mac & windows) under wine, and it seems to work well, but looking around, it seems that only serial devices can be attached to wine as well. Last resort, a windows VM :-( 

Thanks again for your help.
